NomadCars/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NomadCars.DAL;
using NomadCars.Models;

namespace NomadCars.Controllers
{
    /// <summary>
    /// Author: Zeeshan
    /// This controller will allow members of staff to
    /// add, edit, delete, and view cars
    /// </summary>
    //[Authorize(Roles = "Staff")]
    public class CarsController : Controller
    {
        private NomadDbContext db = new NomadDbContext();
        //private Car car;

        // GET: Cars
        [Authorize(Roles = "Staff")]
        public ActionResult Index()
        {
            var cars = db.Cars.Include(c => c.CarSpec);
            return View(cars.ToList());
        }

        // GET: Cars/Details/5
        [Authorize (Roles = "Staff")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Car car = db.Cars.Find(id);
            if (car == null)
            {
                return HttpNotFound();
            }
            return View(car);
        }

        public ActionResult CarDetails(int id)
        {
            Car car = db.Cars.Find(id);

            if (car == null)
            {
                return HttpNotFound();
            }
            return View(car);
          
        }

        // GET: Cars/Create
        public ActionResult Create()
        {
            ViewBag.CarSpecID = new SelectList(db.CarSpecs, "CarSpecID", "CarSpecID");
            return View();
        }

        // POST: Cars/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CarID,Colour,NumberPlate,VINNo,Mileage,TransmissionType,NoPreviousOwner,AccelerationTo60,Sold,Delivered,CO2Emissions,CarSpecID")] Car car)
        {
            if (ModelState.IsValid)
            {
                db.Cars.Add(car);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CarSpecID = new SelectList(db.CarSpecs, "CarSpecID", "CarSpecID", car.CarSpecID);
            return View(car);
        }

        // GET: Cars/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Car car = db.Cars.Find(id);
            if (car == null)
            {
                return HttpNotFound();
            }
            ViewBag.CarSpecID = new SelectList(db.CarSpecs, "CarSpecID", "CarSpecID", car.CarSpecID);
            return View(car);
        }

        // POST: Cars/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CarID,Colour,NumberPlate,VINNo,Mileage,TransmissionType,NoPreviousOwner,AccelerationTo60,Sold,Delivered,CO2Emissions,CarSpecID")] Car car)
        {
            if (ModelState.IsValid)
            {
                db.Entry(car).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CarSpecID = new SelectList(db.CarSpecs, "CarSpecID", "CarSpecID", car.CarSpecID);
            return View(car);
        }

        // GET: Cars/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Car car = db.Cars.Find(id);
            if (car == null)
            {
                return HttpNotFound();
            }
            return View(car);
        }

        // POST: Cars/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Car car = db.Cars.Find(id);
            db.Cars.Remove(car);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NomadCars/Controllers/HomeController.cs
using NomadCars.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NomadCars.Controllers
{
    public class HomeController : Controller
    {
        private NomadDbContext db = new NomadDbContext();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        public ActionResult Finance()
        {
            ViewBag.Message = "Your finance page.";

            return View();
        }


        public ActionResult UsedCars()
        {
            var cars = db.Cars;
            return View(cars.ToList());
        }
    }
}

NomadCars/Controllers/PeopleController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NomadCars.DAL;
using NomadCars.Models;
using PagedList;

namespace NomadCars.Controllers
{
    /// <summary>
    /// Author: William
    /// 
    /// This controller will allow people, both staff
    /// and customers to edit their specific details. 
    /// However, only staff can view or delete 
    /// people's details.
    /// Customers should also only be able to edit their
    /// own details.
    /// </summary>
    
    [Authorize]
    public class PeopleController : Controller
    {
        private NomadDbContext db = new NomadDbContext();
        private Person customer;

        // GET: People        
        [Authorize(Roles = "Staff")]
        public ViewResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParam = sortOrder == "DOB" ? "DOB_desc" : "DOB";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;

            var people = from s in db.People
                         select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                people = people.Where(s => s.LastName.Contains(searchString)
                                    || s.FirstName.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    people = people.OrderByDescending(s => s.LastName);
                    break;
                case "DOB":
                    people = people.OrderBy(s => s.DateOfBirth);
                    break;
                case "DOB_desc":
                    people = people.OrderByDescending(s => s.DateOfBirth);
                    break;
                default:
                    people = people.OrderBy(s => s.LastName);
                    break;
            }

            int pageSize = 4;
            int pageNumber = (page ?? 1);
            return View(people.ToPagedList(pageNumber, pageSize));
        }

        // GET: People/Details/5
        [Authorize(Roles = "Staff")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.People.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            return View(person);
        }

        // GET: People/Details/5
        [Authorize(Roles = "Staff")]
        public ActionResult CustomerDetails()
        {

            string email = User.Identity.Name;
            customer = db.People.Where(p => p.Email == email).Include(s => s.Staff).FirstOrDefault();


            if (customer == null)
            {

                return RedirectToAction("Create");
            }


            return View(customer);
        }
        // GET: People/Create
        public ActionResult Create()
        {
            //ViewBag.PersonID = new SelectList(db.Addresses, "AddressID", "House");
            //ViewBag.PersonID = new SelectList(db.Staff, "StaffID", "Department");

            string email = User.Identity.Name;

            customer = new Person();
            customer.DateOfBirth = new System.DateTime(1990, 1, 1);
            customer.Email = email;
            customer.IsStaff = false;
            customer.IsCustomer = true;

            return View(customer);
        }

        // POST: People/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PersonID,FirstName,LastName,HomePhoneNumber,MobilePhoneNumber,Email,DateOfBirth,MaritalStatus,IsCustomer,IsStaff")] Person person)
        {
            if (ModelState.IsValid)
            {
                db.People.Add(person);
                db.SaveChanges();

                return RedirectToAction("CustomerDetails");
            }

            ViewBag.PersonID = new SelectList(db.Addresses, "AddressID", "House", person.PersonID);
            ViewBag.PersonID = new SelectList(db.Staff, "StaffID", "Department", person.PersonID);
            return View(person);
        }

        // GET: People/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.People.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }

            ViewBag.PersonID = new SelectList(db.Addresses, "AddressID", "House", person.PersonID);
            ViewBag.PersonID = new SelectList(db.Staff, "StaffID", "Department", person.PersonID);

            return View(person);
        }

        // POST: People/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PersonID,FirstName,LastName,HomePhoneNumber,MobilePhoneNumber,Email,DateOfBirth,MaritalStatus,IsCustomer,IsStaff")] Person person)
        {
            if (ModelState.IsValid)
            {
                db.Entry(person).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("CustomerDetails");
            }

            ViewBag.PersonID = new SelectList(db.Addresses, "AddressID", "House", person.PersonID);
            ViewBag.PersonID = new SelectList(db.Staff, "StaffID", "Department", person.PersonID);

            return View(person);
        }

        // GET: People/Delete/5
        [Authorize(Roles = "Staff")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.People.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            return View(person);
        }

        // POST: People/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Staff")]
        public ActionResult DeleteConfirmed(int id)
        {
            Person person = db.People.Find(id);
            db.People.Remove(person);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NomadCars/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact Us";
}
<header class="jumbotron">
    <h1>Nomad Cars</h1>
    <h2>@ViewBag.Title</h2>
</header>

<section class="row">
    <section class="col-lg-4">
        <h2>Address</h2>
        <address>
            Eight Kestrel Way <br />
            Aylesbury, Bucks HP20 1AB<br /> <br />
            Call us on <br /> 07762 123 456
        </address>
        <h2>Support Email</h2>
        <address>
            <a href="mailto:Support@example.com">william.foster@nomad.com</a><br />
        </address>
    </section>
    
    <section class="col-lg-6">
        <h2>Maps Location</h2>
        <address>
            <div class="mapouter">
                <div class="gmap_canvas"><iframe width="600" height="500" id="gmap_canvas" src="https://maps.google.com/maps?q=HP20%201AB&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe><a href="https://www.embedgooglemap.net"></a></div>
                <style>
                    .mapouter {
                        text-align: right;
                        height: 500px;
                        width: 600px;
                    }

                    .gmap_canvas {
                        overflow: hidden;
                        background: none !important;
                        height: 500px;
                        width: 600px;
                    }
                </style>
            </div>

        </address>
    </section>
</section>

NomadCars/Views/Home/Finance.cshtml
@{
    ViewBag.Title = "Finance";
}
<header class="jumbotron">
    <h1>Nomad Cars</h1>
    <h2>@ViewBag.Title</h2>
</header>

NomadCars/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<header class="jumbotron">
    <h1>Nomad Cars</h1>
    <h2>@ViewBag.Title</h2>
</header>
<section id="carousel-cars" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#carousel-cars" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-cars" data-slide-to="1"></li>
        <li data-target="#carousel-cars" data-slide-to="2"></li>
        <li data-target="#carousel-cars" data-slide-to="3"></li>
        <li data-target="#carousel-cars" data-slide-to="4"></li>
    </ol>

    <!-- Wrapper for slides -->
    <section class="carousel-inner" role="listbox">
        <figure class="item active">
            <img src="~/Images/BMW420D.jpg" alt="BMW 420D">
            <figcaption class="carousel-caption">
                <h2>BMW 420D </h2>
            </figcaption>
        </figure>
        <figure class="item">
            <img src="~/Images/BMW116D.jpg" alt="BMW 116D" />
            <figcaption class="carousel-caption">
                <h2> BMW 116D </h2>
            </figcaption>
        </figure>

        <figure class="item">
            <img src="~/Images/BMW330D.jpg" alt=" BMW 330D" />
            <figcaption class="carousel-caption">
                <h2> BMW 330D </h2>
            </figcaption>
        </figure>

        <figure class="item">
            <img src="~/Images/BMWX1.jpg" alt="BMW X1" />
            <figcaption class="carousel-caption">
                <h2> BMW X1 </h2>
            </figcaption>
        </figure>

        <figure class="item">
            <img src="~/Images/BMWI8.jpg" alt="BMW I8" />
            <figcaption class="carousel-caption">
                <h2> BMW I8 </h2>
            </figcaption>
        </figure>

    </section>

    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-cars" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#carousel-cars" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</section>
<section>
    <br />
    <center>
        @Html.ActionLink("Buy or Reserve", "CustomerDetails", "People", null, new { @class = "btn btn-info" })
    </center>
</section>

NomadCars/Views/Home/UsedCars.cshtml
@model IEnumerable<NomadCars.Models.Car>
@using NomadCars.Models

@{
    ViewBag.Title = "Used Cars";
    int imageNo = 0;
}
<header class="jumbotron">
    <h1>Nomad Cars</h1>
    <h2>Currently Available Used Cars</h2>
</header>

@foreach (var car in Model)
{
    <section class="row">
        <section class="col-lg-4">
            @if (car.ImagesList.Count() == 0)
            {
                <img src=" https://via.placeholder.com/350x300" alt="Image of car" title="image of car" />
            }
            else
            {
                var image = car.ImagesList.First();
                <img class="main-car-image" src="@image.ImageURL" alt="@image.Description" title="@image.Caption" style="width:350px;" />
            }
        </section>
        <section class="col-lg-6">
            <h2>@car.CarSpec.Make @car.CarSpec.Model.GetDisplayName()</h2>
            <h4>
                @car.TransmissionType | @car.CarSpec.FuelType.GetDisplayName() |
                @car.NumberPlate | @car.CarSpec.DriveTrain.GetDisplayName() | @car.Mileage miles
            </h4>
            <br /><br /><br />
            @if (car.ImagesList.Count() == 0)
            {
                <img src="https://via.placeholder.com/100x80" alt="Image of car" title="image of car" />
                <img src="https://via.placeholder.com/100x80" alt="front" title="image of car" />
                <img src="https://via.placeholder.com/100x80" alt="left side" title="image of car" />
                <img src="https://via.placeholder.com/100x80" alt="right side" title="image of car" />
                <img src="https://via.placeholder.com/100x80" alt="back" title="image of car" />
            }
            else
            {
                imageNo = 0;
                foreach (var image in car.ImagesList)
                {
                    imageNo++;
                    if (imageNo > 1)
                    {
                        <a href="@image.ImageURL" target="_blank">
                            <img class="small-car-image" src="@image.ImageURL" alt="@image.Description" title="@image.Caption" style="width:100px;" />
                        </a>
                    }
                    
                }
            }
        </section>
        <section class="col-lg-2">
            <center>
                <h2>£@car.Price</h2>
                <br /><br /><br /><br /> <br /><br />

                @Html.ActionLink("View Details", "CarDetails", "Cars", new { id = car.CarID }, new { @class = "btn btn-success" })
            </center>
        </section>
    </section>
    <br /><br />
}