NomadCars/Models/Person.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace NomadCars.Models
{
    public enum MaritalSatusOptions
    {
        [Display(Name ="Single")]
        SINGLE,
        [Display(Name ="Married")]
        MARRIED,
        [Display(Name ="Divorced")]
        DIVORCED,
        [Display(Name ="Other")]
        OTHER
    }

    /// <summary>
    /// William
    /// </summary>
    public class Person
    {
        /// <summary>
        /// A unique number given to a person who 
        /// involves themselves with our cars business,
        /// primarily a customer.
        /// </summary>
        public int PersonID { get; set; }

        /// <summary>
        /// The Forename of any given person.
        /// </summary>
        [Required, StringLength(20), Display(Name = "First Name")]
        public string FirstName { get; set; }

        /// <summary>
        /// The surname of any given person.
        /// </summary>
        [Required, StringLength(20), Display(Name = "Last Name")]
        public string LastName { get; set; }

        /// <summary>
        /// The phone number of a person, assigned to a home phone.
        /// </summary>
        [StringLength(16), DataType(DataType.PhoneNumber), Display(Name = "Home Phone")]
        public string HomePhoneNumber { get; set; }

        /// <summary>
        /// The phone number of a person, assigned to their mobile phone.
        /// </summary>
        [StringLength(16), DataType(DataType.PhoneNumber), Display(Name = "Mobile Phone")]
        public string MobilePhoneNumber { get; set; }

        /// <summary>
        /// The e-mail held by a person by which they can be contacted
        /// </summary>
        [Required, StringLength(100), Display(Name = "E-mail Address")]
        public string Email { get; set; }

        /// <summary>
        /// The date of birth of the person
        /// </summary>
        [Required, DataType(DataType.DateTime), Display(Name = "Date of Birth")] 
        [DisplayFormat(DataFormatString ="{0:yyyy/mm/dd}", ApplyFormatInEditMode = true)]
        public DateTime DateOfBirth { get; set; }

        /// <summary>
        /// The is a current statement of someone's personal relationship status, 
        /// e.g. single, married or divorced. This kind of information is often 
        /// used in forms to determine details such as financial needs.
        /// </summary>
        [Display(Name = "Marital Status")]
        public MaritalSatusOptions MaritalStatus { get; set; }

        /// <summary>
        /// A boolean statement that refers to whether or not the person 
        /// concerned is a customer.
        /// </summary>
        [Display(Name ="Customer")]
        public bool IsCustomer { get; set; }

        // Can be a member of staff and a customer, but must be at least one
        [Display(Name ="Staff")]
        public bool IsStaff { get; set; }

        //public int AdressID { get; set; }

        public virtual Address Address { get; set; }

        public Staff Staff { get; set; }

        public Nullable<int> PaymentCardID { get; set; }

        public ICollection<Purchase> PurchaseList;

        public virtual PaymentCard PaymentCard { get; set; }

        public string FullName
        {
            get { return FirstName + " " + LastName; }
        }

    }
}

NomadCars/Controllers/AddressesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NomadCars.DAL;
using NomadCars.Models;

namespace NomadCars.Controllers
{
    /// <summary>
    /// Author: William 
    /// 
    /// This controller will allow the management 
    /// of people's address data. People can create 
    /// and edit their own individual data but only 
    /// staff can view the table of data, view address
    /// details and delete entries.
    /// </summary>

    [Authorize]
    public class AddressesController : Controller
    {
        private NomadDbContext db = new NomadDbContext();

        // GET: Addresses
        [Authorize(Roles = "Staff")]
        public ActionResult Index()
        {
            var addresses = db.Addresses.Include(a => a.Person);
            return View(addresses.ToList());
        }

        // GET: Addresses/Details/5
        [Authorize(Roles = "Staff")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Address address = db.Addresses.Find(id);
            if (address == null)
            {
                return HttpNotFound();
            }
            return View(address);
        }

        // GET: Addresses/Create
        public ActionResult Create()
        {
            ViewBag.AddressID = new SelectList(db.People, "PersonID", "FullName");
            return View();
        }

        // POST: Addresses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AddressID,House,StreetName,TownName,Postcode,County")] Address address)
        {
            if (ModelState.IsValid)
            {
                db.Addresses.Add(address);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AddressID = new SelectList(db.People, "PersonID", "FirstName", address.AddressID);
            return View(address);
        }

        // GET: Addresses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Address address = db.Addresses.Find(id);
            if (address == null)
            {
                return HttpNotFound();
            }
            ViewBag.AddressID = new SelectList(db.People, "PersonID", "FirstName", address.AddressID);
            return View(address);
        }

        // POST: Addresses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AddressID,House,StreetName,TownName,Postcode,County")] Address address)
        {
            if (ModelState.IsValid)
            {
                db.Entry(address).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("CustomerDetails", "People");
            }
            ViewBag.AddressID = new SelectList(db.People, "PersonID", "FirstName", address.AddressID);
            return View(address);
        }

        // GET: Addresses/Delete/5
        [Authorize(Roles = "Staff")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Address address = db.Addresses.Find(id);
            if (address == null)
            {
                return HttpNotFound();
            }
            return View(address);
        }

        // POST: Addresses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Staff")]
        public ActionResult DeleteConfirmed(int id)
        {
            Address address = db.Addresses.Find(id);
            db.Addresses.Remove(address);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NomadCars/Controllers/PaymentCardsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NomadCars.DAL;
using NomadCars.Models;

namespace NomadCars.Controllers
{

    [Authorize]
    public class PaymentCardsController : Controller
    {
        private NomadDbContext db = new NomadDbContext();

        // GET: PaymentCards
        [Authorize(Roles = "Staff")]
        public ActionResult Index()
        {
            return View(db.PaymentCards.ToList());
        }

        // GET: PaymentCards/Details/5
        [Authorize(Roles = "Staff")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PaymentCard paymentCard = db.PaymentCards.Find(id);
            if (paymentCard == null)
            {
                return HttpNotFound();
            }
            return View(paymentCard);
        }

        // GET: PaymentCards/Create
        public ActionResult Create()
        {
            ViewBag.PaymentCardID = new SelectList(db.People, "PersonID", "FullName");
            return View();
        }

        // POST: PaymentCards/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PaymentCardID,CardType,CardNumber,NameOnCard,SecurityNumber,ExpiryMonth,ExpiryYear")] PaymentCard paymentCard)
        {
            if (ModelState.IsValid)
            {
                db.PaymentCards.Add(paymentCard);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.PaymentCardID = new SelectList(db.People, "PersonID", "FirstName", paymentCard.PaymentCardID);
            return View(paymentCard);
        }

        // GET: PaymentCards/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PaymentCard paymentCard = db.PaymentCards.Find(id);
            if (paymentCard == null)
            {
                return HttpNotFound();
            }
            ViewBag.PaymentCardID = new SelectList(db.People, "PersonID", "FirstName", paymentCard.PaymentCardID);
            return View(paymentCard);
        }

        // POST: PaymentCards/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PaymentCardID,CardType,CardNumber,NameOnCard,SecurityNumber,ExpiryMonth,ExpiryYear")] PaymentCard paymentCard)
        {
            if (ModelState.IsValid)
            {
                db.Entry(paymentCard).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PaymentCardID = new SelectList(db.People, "PersonID", "FirstName", paymentCard.PaymentCardID);
            return View(paymentCard);
        }

        // GET: PaymentCards/Delete/5
        [Authorize(Roles = "Staff")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PaymentCard paymentCard = db.PaymentCards.Find(id);
            if (paymentCard == null)
            {
                return HttpNotFound();
            }
            return View(paymentCard);
        }

        // POST: PaymentCards/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Staff")]
        public ActionResult DeleteConfirmed(int id)
        {
            PaymentCard paymentCard = db.PaymentCards.Find(id);
            db.PaymentCards.Remove(paymentCard);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NomadCars/Controllers/StaffsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NomadCars.DAL;
using NomadCars.Models;

namespace NomadCars.Controllers
{
    /// <summary>
    /// William
    /// 
    /// This controller will enable staff to create and 
    /// manage their own details. Only someone will a staff
    /// role can access these management pages.
    /// </summary>

    [Authorize(Roles = "Staff")]
    public class StaffsController : Controller
    {
        private NomadDbContext db = new NomadDbContext();

        // GET: Staffs
        public ActionResult Index()
        {
            var staff = db.Staff.Include(s => s.Person);
            return View(staff.ToList());
        }

        // GET: Staffs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Staff staff = db.Staff.Find(id);
            if (staff == null)
            {
                return HttpNotFound();
            }
            return View(staff);
        }

        // GET: Staffs/Create
        public ActionResult Create()
        {
            ViewBag.StaffID = new SelectList(db.People, "PersonID", "FullName");
            return View();
        }

        // POST: Staffs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "StaffID,Department,JobPosition,Salary,StartDate,ImageURL,Description")] Staff staff)
        {
            if (ModelState.IsValid)
            {
                db.Staff.Add(staff);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.StaffID = new SelectList(db.People, "PersonID", "FirstName", staff.StaffID);
            return View(staff);
        }

        // GET: Staffs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Staff staff = db.Staff.Find(id);
            if (staff == null)
            {
                return HttpNotFound();
            }
            ViewBag.StaffID = new SelectList(db.People, "PersonID", "FirstName", staff.StaffID);
            return View(staff);
        }

        // POST: Staffs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "StaffID,Department,JobPosition,Salary,StartDate,ImageURL,Description")] Staff staff)
        {
            if (ModelState.IsValid)
            {
                db.Entry(staff).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("CustomerDetails", "People");
            }
            ViewBag.StaffID = new SelectList(db.People, "PersonID", "FirstName", staff.StaffID);
            return View(staff);
        }

        // GET: Staffs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Staff staff = db.Staff.Find(id);
            if (staff == null)
            {
                return HttpNotFound();
            }
            return View(staff);
        }

        // POST: Staffs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Staff staff = db.Staff.Find(id);
            db.Staff.Remove(staff);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NomadCars/Views/People/Create.cshtml
@model NomadCars.Models.Person
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    ViewBag.Title = "Create";
}

<header class="jumbotron">
    <h1>Nomad Cars</h1>
    <h2>@ViewBag.Title</h2>
</header>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Person Details</h4>
        <hr />

        @Html.Partial("_Form")

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NomadCars/Views/People/CustomerDetails.cshtml
@model NomadCars.Models.Person
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{
    ViewBag.Title = "Details";
}
<header class="jumbotron">
    <h1>Nomad Cars</h1>
    <h2>Details of @Model.FullName</h2>

</header>
<section class="row">
    <section class="col-lg-6">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title">Personal Details</h3>
            </div>
            <div class="panel-body">
                <dl class="dl-horizontal">
                    @*@*<dt>
                            @Html.DisplayNameFor(model => model.Address.House)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Address.House)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Staff.Department)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Staff.Department)
                        </dd>*@

                    <dt>
                        @Html.DisplayNameFor(model => model.FirstName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.FirstName)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.LastName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.LastName)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.HomePhoneNumber)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.HomePhoneNumber)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.MobilePhoneNumber)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.MobilePhoneNumber)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Email)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Email)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.DateOfBirth)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.DateOfBirth)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.MaritalStatus)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.MaritalStatus)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.IsCustomer)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.IsCustomer)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.IsStaff)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.IsStaff)
                    </dd>

                </dl>
                <p class="text-right">
                    @Html.ActionLink("Edit Personal Details", "Edit", new { id = Model.PersonID }, new { @class = "btn btn-success" })
                </p>
            </div>
        </div>
    </section>
    <section class="col-lg-6">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title">Address Details</h3>
            </div>
            <div class="panel-body">
                <dl class="dl-horizontal">

                    <dt>
                        @Html.DisplayNameFor(model => model.Address.House)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Address.House)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Address.StreetName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Address.StreetName)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Address.TownName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Address.TownName)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Address.Postcode)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Address.Postcode)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Address.County)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Address.County)
                    </dd>

                </dl>
                <p class="text-right">
                    @Html.ActionLink("Edit Address Details", "Edit", "Addresses", new { id = Model.PersonID }, new { @class = "btn btn-success" })
                </p>
            </div>
        </div>
    </section>
</section>
<section class="row">
    <section class="col-lg-6">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title">Payment Card Details</h3>
            </div>
            <div class="panel-body">
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.PaymentCard.NameOnCard)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.PaymentCard.NameOnCard)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.PaymentCard.CardType)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.PaymentCard.CardType)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.PaymentCard.CardNumber)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.PaymentCard.CardNumber)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.PaymentCard.ExpiryMonth)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.PaymentCard.ExpiryMonth)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.PaymentCard.ExpiryYear)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.PaymentCard.ExpiryYear)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.PaymentCard.SecurityNumber)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.PaymentCard.SecurityNumber)
                    </dd>
                </dl>
                               
                <p class="text-right">
                    @Html.ActionLink("Edit Payment Details", "Edit", "PaymentCards", new { id = Model.PersonID }, new { @class = "btn btn-success" })
                </p>
            </div>
        </div>
    </section>
    <section class="col-lg-6">
        @if (Model.IsStaff)
        {
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title">Staff Details</h3>
                </div>
                <div class="panel-body">
                    <dl class="dl-horizontal">

                        <dt>
                            @Html.DisplayNameFor(model => model.Staff.Department)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Staff.Department)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Staff.JobPosition)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Staff.JobPosition)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Staff.StartDate)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Staff.StartDate)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Staff.Salary)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Staff.Salary)
                        </dd>

                        <dd>
                            <img src="~/Images/Staff/@Model.Staff.ImageURL" alt="Photo of staff" />
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Staff.Description)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Staff.Description)
                        </dd>
                    </dl>
                    <p class="text-right">
                        @Html.ActionLink("Edit Staff Details", "Edit", "Staffs", new { id = Model.PersonID }, new { @class = "btn btn-success" })
                    </p>


                </div>
            </div>
        }
        else
        {
            //a button to proceed to car payment
        }
    </section>
</section>

NomadCars/Views/People/Delete.cshtml
@model NomadCars.Models.Person

@{
    ViewBag.Title = "Delete";
}

<header class="jumbotron">
    <h1>Nomad Cars</h1>
    <h2>@ViewBag.Title</h2>
</header>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Person</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Address.House)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address.House)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Staff.Department)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Staff.Department)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HomePhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HomePhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MobilePhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MobilePhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaritalStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaritalStatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsCustomer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsCustomer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsStaff)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsStaff)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

NomadCars/Views/People/Edit.cshtml
@model NomadCars.Models.Person

@{
    ViewBag.Title = "Edit";
}
<header class="jumbotron">
    <h1>Nomad Cars</h1>
    <h2>Editing Personal Details for @Model.FullName</h2>
</header>

<link href="~/Content/Site.css" rel="stylesheet" />
<link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" />
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>

<script type="text/javascript">
    $(function () {
        $("input:text.date").datepicker({ dateFormat: "dd/MM/yyyy" });
    });
</script>




@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Edit Personal Details</h4>
    <hr />
    
    @Html.Partial("_Form")

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}