NomadCars/Controllers/CarSpecsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NomadCars.DAL;
using NomadCars.Models;

namespace NomadCars.Controllers
{
    public class CarSpecsController : Controller
    {
        private NomadDbContext db = new NomadDbContext();

        // GET: CarSpecs
        public ActionResult Index()
        {
            return View(db.CarSpecs.ToList());
        }

        // GET: CarSpecs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CarSpec carSpec = db.CarSpecs.Find(id);
            if (carSpec == null)
            {
                return HttpNotFound();
            }
            return View(carSpec);
        }

        // GET: CarSpecs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CarSpecs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CarSpecID,Make,Model,EngineSize,Doors,Length,Width,BHP,BootCapacity,Petrol,MPG,Diesel,Electric,Seats,TaxGroup,TopSpeed,DriveTrain,BodyType,Range")] CarSpec carSpec)
        {
            if (ModelState.IsValid)
            {
                db.CarSpecs.Add(carSpec);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(carSpec);
        }

        // GET: CarSpecs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CarSpec carSpec = db.CarSpecs.Find(id);
            if (carSpec == null)
            {
                return HttpNotFound();
            }
            return View(carSpec);
        }

        // POST: CarSpecs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CarSpecID,Make,Model,EngineSize,Doors,Length,Width,BHP,BootCapacity,Petrol,MPG,Diesel,Electric,Seats,TaxGroup,TopSpeed,DriveTrain,BodyType,Range")] CarSpec carSpec)
        {
            if (ModelState.IsValid)
            {
                db.Entry(carSpec).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(carSpec);
        }

        // GET: CarSpecs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CarSpec carSpec = db.CarSpecs.Find(id);
            if (carSpec == null)
            {
                return HttpNotFound();
            }
            return View(carSpec);
        }

        // POST: CarSpecs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CarSpec carSpec = db.CarSpecs.Find(id);
            db.CarSpecs.Remove(carSpec);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NomadCars/Controllers/StaffsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NomadCars.DAL;
using NomadCars.Models;

namespace NomadCars.Controllers
{
    /// <summary>
    /// William
    /// 
    /// This controller will enable staff to create and 
    /// manage their own details. Only someone will a staff
    /// role can access these management pages.
    /// </summary>

    [Authorize(Roles = "Staff")]
    public class StaffsController : Controller
    {
        private NomadDbContext db = new NomadDbContext();

        // GET: Staffs
        public ActionResult Index()
        {
            var staff = db.Staff.Include(s => s.Person);
            return View(staff.ToList());
        }

        // GET: Staffs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Staff staff = db.Staff.Find(id);
            if (staff == null)
            {
                return HttpNotFound();
            }
            return View(staff);
        }

        // GET: Staffs/Create
        public ActionResult Create()
        {
            ViewBag.StaffID = new SelectList(db.People, "PersonID", "FullName");
            return View();
        }

        // POST: Staffs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "StaffID,Department,JobPosition,Salary,StartDate,ImageURL,Description")] Staff staff)
        {
            if (ModelState.IsValid)
            {
                db.Staff.Add(staff);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.StaffID = new SelectList(db.People, "PersonID", "FirstName", staff.StaffID);
            return View(staff);
        }

        // GET: Staffs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Staff staff = db.Staff.Find(id);
            if (staff == null)
            {
                return HttpNotFound();
            }
            ViewBag.StaffID = new SelectList(db.People, "PersonID", "FirstName", staff.StaffID);
            return View(staff);
        }

        // POST: Staffs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "StaffID,Department,JobPosition,Salary,StartDate,ImageURL,Description")] Staff staff)
        {
            if (ModelState.IsValid)
            {
                db.Entry(staff).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("CustomerDetails", "People");
            }
            ViewBag.StaffID = new SelectList(db.People, "PersonID", "FirstName", staff.StaffID);
            return View(staff);
        }

        // GET: Staffs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Staff staff = db.Staff.Find(id);
            if (staff == null)
            {
                return HttpNotFound();
            }
            return View(staff);
        }

        // POST: Staffs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Staff staff = db.Staff.Find(id);
            db.Staff.Remove(staff);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NomadCars/Views/Shared/_Footer.cshtml
<hr />
<footer>
    <div class="row">

        <div class="col-xs-9">
            <p class="text-center"> 
                &copy; @DateTime.Now.Year - Nomad Cars | BNU FD Computing | CO550 Web Applications | CW2 ASP.NET MVC Team Project <br/>
            
            <p class="text-center"> 
                @Html.ActionLink("Home |", "Index", "Home") @Html.ActionLink("Used Cars |", "UsedCars", "Home") @Html.ActionLink("Contact Us |", "Contact", "Home") @Html.ActionLink("Staff Portal", "Index", "Staffs")
            </p>

        </div>

        <div class="col-xs-3">
            <ul>
                <h4> <u>Opening Hours</u> </h4>
                <span class="border-primary">
                    <li>Monday - Friday : 9am - 6pm</li>
                    <li>Saturday : 9am - 7pm</li>
                    <li>Sunday : 10am - 4pm</li>
                </span>
            </ul>
            
        </div>

    </div>
    <hr />
</footer>

NomadCars/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Nomad Cars</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nomad Cars", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Used Cars", "UsedCars", "Home")</li>
                    <li>@Html.ActionLink("Contact Us", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Finance", "Finance", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        @Html.Partial("_Footer");
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

NomadCars/Views/Shared/_StaffLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Nomad Cars</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nomad Cars", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("People", "Index", "People")</li>
                    <li>@Html.ActionLink("Staff", "Index", "Staffs")</li>
                    <li>@Html.ActionLink("Addresses", "Index", "Addresses")</li>
                    <li>@Html.ActionLink("Car Models", "Index", "CarSpecs")</li>
                    <li>@Html.ActionLink("Cars", "Index", "Cars")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        @Html.Partial("_Footer");
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script>
        $(function ()
        {
            $( "#StartDate" ).datepicker();
        } );
    </script>
</body>
</html>